/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-06-16 05:52:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.LikeDTO;
import model.LikeDAO;
import java.util.ArrayList;
import model.CommentDAO;
import java.util.List;
import model.MemberDTO;
import org.apache.ibatis.reflection.SystemMetaObject;
import model.BoardDAO;
import model.BoardVO;
import model.CommentVO;

public final class BoardDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1308849601000L));
    _jspx_dependants.put("jar:file:/C:/Users/smhrd1/Desktop/BackStudy/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Project1/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(10);
    _jspx_imports_classes.add("org.apache.ibatis.reflection.SystemMetaObject");
    _jspx_imports_classes.add("model.BoardDAO");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.LikeDAO");
    _jspx_imports_classes.add("model.MemberDTO");
    _jspx_imports_classes.add("model.BoardVO");
    _jspx_imports_classes.add("model.CommentVO");
    _jspx_imports_classes.add("model.LikeDTO");
    _jspx_imports_classes.add("model.CommentDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<!--\r\n");
      out.write("	Arcana by HTML5 UP\r\n");
      out.write("	html5up.net | @ajlkn\r\n");
      out.write("	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)\r\n");
      out.write("-->\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>농부 초기자본계산사이트</title>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/main.css\" />\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("img.contentimg {\r\n");
      out.write("	width: 50%;\r\n");
      out.write("	height: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title {\r\n");
      out.write("	font-size: 72px;\r\n");
      out.write("	background: linear-gradient(to bottom, green, yellow);\r\n");
      out.write("	-webkit-background-clip: text;\r\n");
      out.write("	-webkit-text-fill-color: transparent;\r\n");
      out.write("}\r\n");
      out.write("h1 {\r\n");
      out.write("	font-size: 30px;\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"is-preload\">\r\n");
      out.write("	");

	MemberDTO user_info = (MemberDTO) session.getAttribute("user_info");
	
	
      out.write("\r\n");
      out.write("	<div id=\"page-wrapper\">\r\n");
      out.write("\r\n");
      out.write("		<!-- Header -->\r\n");
      out.write("		<div id=\"header\">\r\n");
      out.write("\r\n");
      out.write("			<!-- Logo -->\r\n");
      out.write("			<h1>\r\n");
      out.write("				<a href=\"Main.jsp\" class=\"title\"> <Strong>농부樂</Strong></a>\r\n");
      out.write("			</h1>\r\n");
      out.write("\r\n");
      out.write("			<!-- Nav -->\r\n");
      out.write("			<nav id=\"nav\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"Main.jsp\">Home</a></li>\r\n");
      out.write("					<li><a href=\"Calculator.jsp\">계산기</a></li>\r\n");
      out.write("					<li class=\"current\"><a href=\"BoardMain.jsp\">게시판</a></li>\r\n");
      out.write("					\r\n");
      out.write("				</ul>\r\n");
      out.write("			</nav>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Main -->\r\n");
      out.write("		<section class=\"wrapper style1\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row gtr-200\">\r\n");
      out.write("					<div class=\"col-3 col-12-narrower\">\r\n");
      out.write("						<div id=\"sidebar1\">\r\n");
      out.write("\r\n");
      out.write("							<!-- Sidebar 1 -->\r\n");
      out.write("\r\n");
      out.write("							\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-6 col-12-narrower imp-narrower\">\r\n");
      out.write("						<div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("							<!-- Content -->\r\n");
      out.write("\r\n");
      out.write("							<article>\r\n");
      out.write("								<header>\r\n");
      out.write("									<h2>자유게시판</h2>\r\n");
      out.write("								</header>\r\n");
      out.write("\r\n");
      out.write("								<span class=\"image featured\"><img src=\"images/banner.jpg\"\r\n");
      out.write("									alt=\"\" /></span>\r\n");
      out.write("\r\n");
      out.write("								");

								int num = Integer.parseInt(request.getParameter("num"));
								BoardVO board = new BoardDAO().detailBoard(num);

								ArrayList<CommentVO> cvo = new CommentDAO().allcoment(board.getB_idx());
								pageContext.setAttribute("cvo", cvo);
								LikeDTO dto = new LikeDTO(board.getB_idx(),user_info.getId());
								LikeDTO dto1 = new LikeDTO(board.getB_idx());
								int like_cnt = new LikeDAO().like_count(dto1);
								
      out.write("\r\n");
      out.write("								<div id=\"board\">\r\n");
      out.write("									<table>\r\n");
      out.write("										<tr>\r\n");
      out.write("											<td><strong>제목</strong></td>\r\n");
      out.write("											<td>");
      out.print(board.getTitle());
      out.write("</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("										<tr>\r\n");
      out.write("											<td><strong>작성자</strong></td>\r\n");
      out.write("											<td>");
      out.print(board.getId());
      out.write("</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("										\r\n");
      out.write("										<tr>\r\n");
      out.write("											<td colspan=\"2\"><br></td>\r\n");
      out.write("										</tr>\r\n");
      out.write("										<hr>\r\n");
      out.write("										<tr>\r\n");
      out.write("											<td colspan=\"2\">\r\n");
      out.write("												<fieldset><legend>Content</legend>\r\n");
      out.write("												<p style=\"font-size: 15px;\"> <br> ");
      out.print(board.getContent());
      out.write("<br></p>\r\n");
      out.write("												</fieldset>\r\n");
      out.write("												\r\n");
      out.write("											</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("									</table>\r\n");
      out.write("									<table>\r\n");
      out.write("										<tr>\r\n");
      out.write("											<td> <strong>작성자</strong> </td>\r\n");
      out.write("											<td><strong>댓글</strong></td>\r\n");
      out.write("											<td><strong>삭제</strong></td>\r\n");
      out.write("										</tr>\r\n");
      out.write("										");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      boolean _jspx_th_c_005fforEach_005f0_reused = false;
      try {
        _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fforEach_005f0.setParent(null);
        // /BoardDetail.jsp(138,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setVar("b");
        // /BoardDetail.jsp(138,10) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/BoardDetail.jsp(138,10) '${cvo}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${cvo}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
        int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
          if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\r\n");
              out.write("											<tr>\r\n");
              out.write("												<td>");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.mem_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</td>\r\n");
              out.write("												<td>");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.comment_content }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</td>\r\n");
              out.write("												<td><a\r\n");
              out.write("													href=\"CommentDel.do?com_id=");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.comment_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("&mem_id=");
              out.print(user_info.getId());
              out.write("\">삭제</a></td>\r\n");
              out.write("											</tr>\r\n");
              out.write("										");
              int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_c_005fforEach_005f0.doFinally();
        }
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
        _jspx_th_c_005fforEach_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
      }
      out.write("\r\n");
      out.write("									</table>\r\n");
      out.write("									\r\n");
      out.write("									\r\n");
      out.write("									<button>\r\n");
      out.write("									<a href=\"LikeCon.do?b_idx=");
      out.print(board.getB_idx());
      out.write("&mem_id=");
      out.print( user_info.getId());
      out.write("\">좋아요</a>\r\n");
      out.write("									<p>");
      out.print(like_cnt );
      out.write("</p></button>\r\n");
      out.write("											\r\n");
      out.write("									");

									if (user_info != null) {
									
      out.write("\r\n");
      out.write("									<form action=\"CommentWrite.do\" method=\"post\">\r\n");
      out.write("										<table>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<td >댓글<input type=\"hidden\" NAME=\"mem_id\"\r\n");
      out.write("													value=\"");
      out.print(user_info.getId());
      out.write("\"> <input\r\n");
      out.write("													type=\"hidden\" NAME=\"b_idx\" value=\"");
      out.print(board.getB_idx());
      out.write("\">\r\n");
      out.write("												</td>\r\n");
      out.write("												<td><input type=\"text\" maxlength='400' name=\"content\" ></td>\r\n");
      out.write("												<td><input type=\"submit\" value=\"작성하기\" ></td>\r\n");
      out.write("											</tr>\r\n");
      out.write("										</table>\r\n");
      out.write("									</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("									\r\n");
      out.write("\r\n");
      out.write("									");

									}else{
									
      out.write("\r\n");
      out.write("									<form action=\"\" method=\"post\">\r\n");
      out.write("										<table>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<td>댓글\r\n");
      out.write("												</td>\r\n");
      out.write("												<td><input type=\"text\" maxlength='400' name=\"content\" placeholder=\"로그인하세요\"></td>\r\n");
      out.write("												<td><input type=\"submit\" value=\"작성하기\"></td>\r\n");
      out.write("											</tr>\r\n");
      out.write("										</table>\r\n");
      out.write("									</form>\r\n");
      out.write("									\r\n");
      out.write("									");

									}
									
      out.write("\r\n");
      out.write("									<button>\r\n");
      out.write("										<a href=\"BoardMain.jsp\">뒤로가기</a>\r\n");
      out.write("									</button>\r\n");
      out.write("\r\n");
      out.write("								</div>\r\n");
      out.write("							</article>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-3 col-12-narrower\">\r\n");
      out.write("						<div id=\"sidebar2\">\r\n");
      out.write("\r\n");
      out.write("							<!-- Sidebar 2 -->\r\n");
      out.write("\r\n");
      out.write("							\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Scripts -->\r\n");
      out.write("		<script src=\"assets/js/jquery.min.js\"></script>\r\n");
      out.write("		<script src=\"assets/js/jquery.dropotron.min.js\"></script>\r\n");
      out.write("		<script src=\"assets/js/browser.min.js\"></script>\r\n");
      out.write("		<script src=\"assets/js/breakpoints.min.js\"></script>\r\n");
      out.write("		<script src=\"assets/js/util.js\"></script>\r\n");
      out.write("		<script src=\"assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
