/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-06-13 00:24:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.MemberDTO;
import model.MemberDAO;

public final class Main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("model.MemberDAO");
    _jspx_imports_classes.add("model.MemberDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE HTML>\n");
      out.write("<!--\n");
      out.write("   Arcana by HTML5 UP\n");
      out.write("   html5up.net | @ajlkn\n");
      out.write("   Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)\n");
      out.write("-->\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>농부 초기자본계산사이트</title>\n");
      out.write("<meta charset=\"utf-8\" />\n");
      out.write("<meta name=\"viewport\"\n");
      out.write("   content=\"width=device-width, initial-scale=1, user-scalable=no\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/main.css\" />\n");
      out.write("<style type=\"text/css\">\n");
      out.write("button#sign {\n");
      out.write("   margin-left: 1000px;\n");
      out.write("   margin-bottom: 20px;\n");
      out.write("   background-color: #9acd32;\n");
      out.write("}\n");
      out.write("\n");
      out.write("button#login {\n");
      out.write("   margin-left: 10px;\n");
      out.write("   background-color: #9acd32;\n");
      out.write("}\n");
      out.write("\n");
      out.write("button#mypage {\n");
      out.write("   margin-left: 1000px;\n");
      out.write("   margin-bottom: 20px;\n");
      out.write("   background-color: #9acd32;\n");
      out.write("}\n");
      out.write("button#admin {\n");
      out.write("   margin-left: 1000px;\n");
      out.write("   margin-bottom: 20px;\n");
      out.write("   background-color: #9acd32;\n");
      out.write("}\n");
      out.write("\n");
      out.write("button#logout {\n");
      out.write("   margin-left: 10px;\n");
      out.write("   background-color: #9acd32;\n");
      out.write("}\n");
      out.write("\n");
      out.write("h1 {\n");
      out.write("   font-size: 30px;\n");
      out.write("   color: black;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".title{\n");
      out.write("    font-size: 72px;\n");
      out.write("     background: linear-gradient(to bottom, green, yellow);\n");
      out.write("     -webkit-background-clip: text;\n");
      out.write("    -webkit-text-fill-color: transparent;\n");
      out.write("}\n");
      out.write("\n");
      out.write("a#join {\n");
      out.write("   color: black;\n");
      out.write("}\n");
      out.write("\n");
      out.write("a#login {\n");
      out.write("   color: black;\n");
      out.write("}\n");
      out.write("\n");
      out.write("a#mypage {\n");
      out.write("   color: black;\n");
      out.write("}\n");
      out.write("\n");
      out.write("a#logout {\n");
      out.write("   color: black;\n");
      out.write("}\n");
      out.write("a{\n");
      out.write("   color: black;\n");
      out.write("}\n");
      out.write("li{\n");
      out.write("   list-style-type: none;\n");
      out.write("   font-size: 25px;\n");
      out.write("}\n");
      out.write("h3{\n");
      out.write("   font-size: 30px;\n");
      out.write("   margin-left: 30px;\n");
      out.write("   margin-bottom: 15px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body class=\"is-preload\">\n");
      out.write("   ");

   MemberDTO user_info = (MemberDTO) session.getAttribute("user_info");
   
      out.write("\n");
      out.write("   <div id=\"page-wrapper\">\n");
      out.write("\n");
      out.write("      <!-- Header -->\n");
      out.write("      <div id=\"header\">\n");
      out.write("\n");
      out.write("         <!-- Logo -->\n");
      out.write("         <h1>\n");
      out.write("            <a href=\"Main.jsp\" class=\"title\"><Strong>농부樂</Strong></a>\n");
      out.write("         </h1>\n");
      out.write("         ");

         if (user_info != null) {
         
      out.write("\n");
      out.write("         ");

         if (user_info.getId().equals("admin")) {
         
      out.write("\n");
      out.write("         <button id=\"admin\"><a href=\"adminpage.jsp\">관리자 페이지</a></button> \n");
      out.write("         <button id=\"logout\">\n");
      out.write("            <a href=\"LogoutCon.do\" id=\"Logout\">로그아웃</a>\n");
      out.write("         </button>\n");
      out.write("          \n");
      out.write("         ");
} else {
      out.write("\n");
      out.write("         <button id=\"mypage\">\n");
      out.write("            <a href=\"Mypage.jsp\" id=\"mypage\">마이페이지</a>\n");
      out.write("         </button>\n");
      out.write("         <button id=\"logout\">\n");
      out.write("            <a href=\"LogoutCon.do\" id=\"logout\">로그아웃</a>\n");
      out.write("         </button>\n");
      out.write("         ");

         }
         
      out.write("\n");
      out.write("         ");

         } else {
         
      out.write("\n");
      out.write("         <button id=\"sign\">\n");
      out.write("            <a href=\"Join.jsp\" id=\"join\">회원가입</a>\n");
      out.write("         </button>\n");
      out.write("         <button id=\"login\">\n");
      out.write("            <a href=\"Login.jsp\" id=\"login\">로그인</a>\n");
      out.write("         </button>\n");
      out.write("         ");

         }
         
      out.write("\n");
      out.write("         <!-- Nav -->\n");
      out.write("         <nav id=\"nav\">\n");
      out.write("            <ul>\n");
      out.write("               <li class=\"current\"><a href=\"Main.jsp\">Home</a></li>\n");
      out.write("               <li><a href=\"Calculator.jsp\">계산기</a></li>\n");
      out.write("               <li><a href=\"BoardMain.jsp\">게시판</a></li>\n");
      out.write("            </ul>\n");
      out.write("         </nav>\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <!-- Banner -->\n");
      out.write("      <section id=\"banner\">\n");
      out.write("               <header>\n");
      out.write("                  <h2>환영합니다!</h2><br>\n");
      out.write("                  <h2>Copyright 2024. Trinity 농부樂.all rights reserved. </h2>\n");
      out.write("               </header>\n");
      out.write("      </section>\n");
      out.write("      \n");
      out.write("      <!-- <h3> [사이트 이용안내] </h3>\n");
      out.write("         <ul>\n");
      out.write("            <li><b> 저희 사이트는 초기자본을 계산해줍니다.</b></li>\n");
      out.write("            <li><b> 1. 회원가입 하기 </b></li>\n");
      out.write("            <li><b> 2. 로그인 하기 </b></li>\n");
      out.write("            <li><b> 3. 계산기 클릭한후 계산하세요. </b></li>\n");
      out.write("            <li><b> 4. 게신판에는 사람들과 소통 및 공유를 할 수 있습니다. </b></li>\n");
      out.write("            <li><b> 5. 가급적 게시판 이용시 안좋은 말은 삼가해주시면 좋겠습니다. </b></li><br>\n");
      out.write("            <li><b><i> <strong> 저희는 예비농부들을 위해 최선을 다해 사이트의 도움이 되도록 노력하겠습니다.</strong></i> </b></li>\n");
      out.write("         </ul> -->\n");
      out.write("\n");
      out.write("      <!-- Scripts -->\n");
      out.write("      <script src=\"assets/js/jquery.min.js\"></script>\n");
      out.write("      <script src=\"assets/js/jquery.dropotron.min.js\"></script>\n");
      out.write("      <script src=\"assets/js/browser.min.js\"></script>\n");
      out.write("      <script src=\"assets/js/breakpoints.min.js\"></script>\n");
      out.write("      <script src=\"assets/js/util.js\"></script>\n");
      out.write("      <script src=\"assets/js/main.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
